config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get "log_in", to: "sessions#new"
  post "log_in", to: "sessions#create"
  post "log_out", to: "sessions#destroy"

  get "sign_up", to: "users#new"


  resources :users
  resources :characters, only: [:index, :show]
  resources :locations, only: [:show, :index]
  resources :items
  resources :sessions

  get '/locations/:id/pickup', to: 'items#pickup'
  get '/locations/:id/details', to: 'locations#details'
  get '/locations/:id/current_items', to: 'locations#current_items'
  get '/locations/:id/set_current_location', to: 'locations#set_current_location', as: 'set_current_location'

  post 'drop_item/:id', to: "items#drop_item", as: 'drop_item'
  post '/locations/:id/next_plot', to: "locations#next_plot", as: 'next_plot'

end

app/models/character.rb
class Character < ActiveRecord::Base
	has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :location
  belongs_to :character
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def authenticate
    if session[:user_id].nil?      
    redirect_to :controller => "sessions", :action => "create"
    flash[:notice] = "You must log in to play the game!"
    end
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
	
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def pickup	
		@character = Character.first
		@location = Location.find(params[:id])
		pickup = @location.items.find do |item|
			item.name == params[:item]
		end
		grab_item(pickup)
	end

	def drop_item
		@item = Item.find(params[:id])
		@item.character_id = nil
		@item.save
		redirect_to :back, notice: "you've dropped #{@item.name}"
	end

	def grab_item(pickup)
		respond_to do |format|
			if @location.items.include?(pickup)
				@character.items << pickup
				format.html { redirect_to :back, notice: "You've picked up the #{pickup.name}!"}
			else
				format.html { redirect_to :back, alert: "Sorry, that item either isn't here, you've already grabbed it, or you've typed the wrong name. Try again!"}
			end
		end
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

	before_filter :authenticate
	
	def set_current_location
		# binding.pry
		@character = Character.first
		@new_location = Location.find(params[:id].to_i + 1)
		@character.items.each do |item|
			item.location_id = @new_location.id
			item.save
		end
		@character.save

		redirect_to @new_location
		# binding.pry
	end

	def show

		@location = Location.find(params[:id])



	end

	# have the array hidden on the page and have the first sentence visible, 
	# jquery on click next, swap out the next sentence 


	def details
		@location = Location.find(params[:id])
		render "details"
	end
	
	def current_items
		@location = Location.find(params[:id])
		@character = Character.first
		render "current_items"
	end
end

app/controllers/logic_controller.rb
class LogicController < ApplicationController

	def attempt_to_proceed
		# call this method when a player clicks go to next chapter
		# iterate through their items to see if they have what is required
		# OR certain key items / lack thereof can affect the outcome of the store
		# You may want a different action for each chapter because it will get fairly specific

		# if there is a new outcome then the location text (both plot and details) will have to change
		# also have to figure out a way to block someone from simply typing in the next location in the address bar
		redirect_to set_current_location_path
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password]) 
			session[:user_id] = @user.id
			redirect_to root_path, notice: "You have successfully logged in!"
    else
    	@user = User.new
    	flash[:error] = "Bad Username or Password"
    	render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
    flash[:notice] = "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save 
  		session[:user_id] = @user.id

      redirect_to root_path, :notice => "Thank you for signing up!"
  	else
  		flash[:alert] = "There was a problem with your signup form. Please try again!"
  		redirect_to :back
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logic_helper.rb
module LogicHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Save Game</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/locations/<%= @location.id %>">Main Story</a></li>
        <li><a href="/locations/<%= @location.id %>/details">Look Around</a></li>
        <li><a href="/locations/<%= @location.id %>/current_items">View Inventory</a></li>
        <li><%= link_to "Go to next Chapter", set_current_location_path %></li>        
      </ul>
      <form class="navbar-form navbar-left" role="search" action="/locations/<%= @location.id %>/pickup">
        <div class="form-group">
        	<input type="text" name="item" class="form-control" placeholder="Enter item">
      		<input type="submit" class="btn btn-default" value="Search Area">
        </div>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

	<% if flash[:notice] %>
		<div class="alert alert-dismissible alert-success">
		  <a href class="close" data-dismiss="alert">x</a>
		  <strong><%= flash[:notice] %></strong>
		</div>
	<% elsif flash[:alert] %>
	
		<div class="alert alert-dismissible alert-danger">
		  <a href class="close" data-dismiss="alert">x</a>
			<strong><%= flash[:alert] %></strong>
		</div>

  <% end %>

  <title>JOURNEY</title>

	<div class="container-fluid">

		<% if logged_in? %>
			<h5><%= current_user.email %>
			<%= link_to "Log Out", log_out_path, method: :destroy, class: 'btn btn-warning btn-xs', style: 'margin-bottom: 10px; float: right;' %></h5>
		<% else %>
			<h5><%= link_to "Sign Up", sign_up_path %> |
			<%= link_to "Log In", new_session_path %></h5>
		<% end %>
	</div>


	<% if @location.nil? %>

		<% yield %>
	
	<% end %>

	<% unless @location.nil? %>
	
	<div class="container-fluid">
		<% if @location.id == 1 %>
			<title>Chapter 1: The Apartment</title>
			<h2>Chapter 1: The Apartment</h2>
		<% elsif @location.id == 2 %>
			<title>Chapter 2: The Street</title>
			<h2>Chapter 2: The Street</h2>
		<% elsif @location.id == 3 %>
			<title>Chapter 3: The Edge of Town</title>
			<h2>Chapter 3: Edge of Town</h2>
		<% elsif @location.id == 4 %>
			<title>Chapter 4: The Bunker</title>
			<h2>Chapter 4: The Bunker</h2>
		<% end %>
		
	</div>
		<%= render "layouts/navbar" %>

	<% end %>

</head>
<body>

<% if @location.nil? %>

<% yield %>

<% end %>

<%= yield %>

</body>
</html>

app/views/locations/_pickup.html.erb
<div>
	<%= form_tag("/locations/#{@location.id}/pickup") do %>

		<p>
			<%= label_tag(:item, "Enter Item:") %> 
			<%= text_field_tag(:item) %>
		</p>
		
		<%= submit_tag("Pick up!") %>
		
	<% end %>
</div>

app/views/locations/_plot.html.erb
<div id="location-plot" hidden><%= @location.plot %></div>


<div class="container-fluid" id="reading-container">

	<div id="plot-text">

		</div>
				<div id="next-button">
			<button id="next"class="btn btn-success">Next</button>
		</div>

</div>

app/views/locations/current_items.html.erb
<% unless @character.items.empty? %>

<div class="container-fluid">
	<h3>You are currently holding:</h3>
</div>

<div class="col-lg-4">
	<div class="list-group">
		<% @character.items.each do |item| %>

			<a href="#" class="list-group-item">
				<h4 class="list-group-item-heading"><%= item.name.capitalize %>:</h4> 
				<p class="list-group-item-text"><%= item.description.capitalize %></p>
				<p><%= button_to 'Drop item', drop_item_path(item), class: "btn btn-default" %></p>
			</a>

			<% end %>


	</div>
</div>

	<% else %>

<div class="container-fluid">
	<p>You are not currently holding anything.</p>
</div>

<% end %>

app/views/locations/details.html.erb
<div class="container-fluid">
	<div class="well">
		<p><%= @location.details %></p>
	</div>
</div>

app/views/locations/pickup.html.erb
<div>
	<%= form_tag("/locations/#{@location.id}/pickup", method: "post") do %>

		<p>
			<%= label_tag(:item, "Enter Item:") %> 
			<%= text_field_tag(:item) %>
		</p>
		
		<%= submit_tag("Pick up!") %>
		
	<% end %>
</div>

<% if flash[:notice] %>
  <p>
    <%= flash[:notice] %>
  </p>
<% end %>

app/views/locations/show.html.erb
<%= render "plot" %>

app/views/users/new.html.erb
<div class="container-fluid">
	<h1>Sign Up</h1>
		<%= form_for @user do |f| %>
			<% if @user.errors.any? %>
				<div class="error_messages">
					<h2>Form is invalid</h2>
					<ul>
						<% for message in @user.errors.full_messages %>
							<li><%= message %></li>
						<% end %>
					</ul>
				</div>
			<% end %>

			<p>
				<%= f.label :email %><br>
				<%= f.text_field :email %>
			</p>

			<p>
				<%= f.label :password %><br>
				<%= f.password_field :password %>
			</p>

			<p>
				<%= f.label :password_confirmation %><br>
				<%= f.password_field :password_confirmation %>
			</p>	

			<button action="submit" class="btn btn-success">Create Account</button>

		<% end %>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
		<div class="container-fluid">
		  <h1>The Perilous Journey</h1>
		  <p class="lead">An adventure game</p>
		</div>
</div>
	
<div class="col-lg-4">
	<div class="well">
		<p>
			In this game you play the role of a Russian soldier who has gotten cut off from their unit. Your goal is to proceed through each chapter by reading the text for clues and picking up objects in each area. There are certain items that you must have in your possession in order to move on. 
		</p>
	</div>
</div>

<div class="col-lg-4">
	<div class="well">
		<p>
			In order to pick up an item, you must enter the correct name of the item in the "pick up item" input field in order for it to be added to your character's inventory. If you have picked up the right item, you'll be able to click "go to next location" and proceed to the next chapter. You should strive to pick up as many items as you can find in each setting - an item from chapter 1 may save your life in chapter 4, for example.
		</p>
	</div>
</div>

<div class="col-lg-4">
	<div class="well">
		<p>
			Your goal is to survive through all four chapters and join back up with your unit.
		</p>
		<p>Shall we begin?</p>
		<a href="/locations/1" class="btn btn-success">Let's do this</a>
	</div>
</div>